development: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  reconnect: false
  database: <%= 'qa_test' %>
  pool: 30
  username: <%= 'root' %>
  password: <%= '' %>
  host: <%= 'localhost' %>
  port: 3306
  reaping_frequency: 300

production:
  <<: *default

staging:
  <<: *default

qa:
  <<: *default

test:
  <<: *default
  database: <%= 'qa_test_test' %>
